export const SignupConstants = {
  SIGN_UP_LOADING: 'SIGN_UP_LOADING',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',
}
export const EmailVerifyConstants = {
  EMAIL_VERIFY_LOADING: 'EMAIL_VERIFY_LOADING',
  EMAIL_VERIFY_SUCCESS: 'EMAIL_VERIFY_SUCCESS',
  EMAIL_VERIFY_ERROR: 'EMAIL_VERIFY_ERROR',
}

export const UserDataConstants = {
  USER_DATA_LOADING: 'USER_DATA_LOADING',
  USER_DATA_SUCCESS: 'USER_DATA_SUCCESS',
  USER_DATA_ERROR: 'USER_DATA_ERROR',
}

export const SignInConstants = {
  SIGN_IN_LOADING: 'SIGN_IN_LOADING',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',
}

export const DarkModeConstants = {
  DARK_MODE_LOADING: 'DARK_MODE_LOADING',
  DARK_MODE_SUCCESS: 'DARK_MODE_SUCCESS',
  DARK_MODE_ERROR: 'DARK_MODE_ERROR',
}
export const ForgetPasswordConstants = {
  FORGET_PASSWORD_LOADING: 'FORGET_PASSWORD_LOADING',
  FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',
  FORGET_PASSWORD_ERROR: 'FORGET_PASSWORD_ERROR',
}

export const ResetPasswordConstants = {
  RESET_PASSWORD_LOADING: 'RESET_MODE_LOADING',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_ERROR: 'RESET_PASSWORD_ERROR',
}
export const GetAllBarberConstants = {
  BARBER_LOADING: 'BARBER_LOADING',
  BARBER_SUCCESS: 'BARBER_SUCCESS',
  BARBER_ERROR: 'BARBER_ERROR',
}
export const GetABarberConstants = {
  BARBER_LOADING: 'BARBER_LOADING',
  BARBER_SUCCESS: 'BARBER_SUCCESS',
  BARBER_ERROR: 'BARBER_ERROR',
}
export const GetAllSchedules = {
  GET_ALL_SCHEDULE_LOADING: 'GET_ALL_SCHEDULE_LOADING',
  GET_ALL_SCHEDULE_SUCCESS: 'GET_ALL_SCHEDULE_SUCCESS',
  GET_ALL_SCHEDULE_ERROR: 'GET_ALL_SCHEDULE_ERROR',
}
export const UploadImageConstants = {
  UPLOAD_IMAGE_LOADING: 'UPLOAD_IMAGE_LOADING',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  UPLOAD_IMAGE_ERROR: 'UPLOAD_IMAGE_ERROR',
}
export const GetUserProfileConstants = {
  GET_USER_PROFILE_LOADING: 'GET_USER_PROFILE_LOADING',
  GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
  GET_USER_PROFILE_ERROR: 'GET_USER_PROFILE_ERROR',
}
export const UpdateUserProfileContants = {
  UPDATE_USER_PROFILE_LOADING: 'UPDATE_USER_PROFILE_LOADING',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_ERROR: 'UPDATE_USER_PROFILE_ERROR',
}
export const GetBarberScheduleConstant = {
  GET_BARBER_SCHEDULE_LOADING: 'GET_BARBER_SCHEDULE_LOADING',
  GET_BARBER_SCHEDULE_SUCCESS: 'GET_BARBER_SCHEDULE_SUCCESS',
  GET_BARBER_SCHEDULE_ERROR: 'GET_BARBER_SCHEDULE_ERROR',
}
export const AddPackageDetailConstant = {
  ADD_PACKAGE_DETAIL_LOADING: 'ADD_PACKAGE_DETAIL_LOADING',
  ADD_PACKAGE_DETAIL_SUCCESS: 'ADD_PACKAGE_DETAIL_SUCCESS',
  ADD_PACKAGE_DETAIL_ERROR: 'ADD_PACKAGE_DETAIL_ERROR',
}

export const ServiceSelectedConstants = {
  SERVICE_SELECTED_LOADING: 'SERVICE_SELECTED_LOADING',
  SERVICE_SELECTED_SUCCESS: 'SERVICE_SELECTED_SUCCESS',
  SERVICE_SELECTED_ERROR: 'SERVICE_SELECTED_ERROR',
}

export const GetAllServicesByBarberIdConstants = {
  GET_ALL_SERVICES_ID_LOADING: 'GET_ALL_SERVICES_ID_LOADING',
  GET_ALL_SERVICES_ID_SUCCESS: 'GET_ALL_SERVICES_ID_SUCCESS',
  GET_ALL_SERVICES_ID_ERROR: 'GET_ALL_SERVICES_ID_ERROR',
}

export const GetAllServicesConstant = {
  GET_ALL_SERVICES_LOADING: 'GET_ALL_SERVICES_LOADING',
  GET_ALL_SERVICES_SUCCESS: 'GET_ALL_SERVICES_SUCCESS',
  GET_ALL_SERVICES_ERROR: 'GET_ALL_SERVICES_ERROR',
}

export const CreateBookingConstants = {
  CREATE_BOOKING_LOADING: 'CREATE_BOOKING_LOADING',
  CREATE_BOOKING_SUCCESS: 'CREATE_BOOKING_SUCCESS',
  CREATE_BOOKING_ERROR: 'CREATE_BOOKING_ERROR',
}
export const GetAllPackagesConstatnts = {
  GET_ALL_PACKAGES_LOADING: 'GET_ALL_PACKAGES_LOADING',
  GET_ALL_PACKAGES_SUCCESS: 'GET_ALL_PACKAGES_SUCCESS',
  GET_ALL_PACKAGES_ERROR: 'GET_ALL_PACKAGES_ERROR',
}
export const GetAllPackagesByTypeConstants = {
  GET_ALL_PACKAGES_BY_TYPE_LOADING: 'GET_ALL_PACKAGES_BY_TYPE_LOADING',
  GET_ALL_PACKAGES_BY_TYPE_SUCCESS: 'GET_ALL_PACKAGES_BY_TYPE_SUCCESS',
  GET_ALL_PACKAGES_BY_TYPE_ERROR: 'GET_ALL_PACKAGES_BY_TYPE_ERROR',
}
export const GetAllServiceByIdConstatnts = {
  GET_ALL_SERVICE_BY_ID_LOADING: 'GET_ALL_SERVICE_BY_ID_LOADING',
  GET_ALL_SERVICE_BY_ID_SUCCESS: 'GET_ALL_SERVICE_BY_ID_SUCCESS',
  GET_ALL_SERVICE_BY_ID_ERROR: 'GET_ALL_SERVICE_BY_ID_ERROR',
}
export const RescheduleAppointmentConstant = {
  RESHEDULE_APPOINTMENT_LOADING: 'RESHEDULE_APPOINTMENT_LOADING',
  RESHEDULE_APPOINTMENT_SUCCESS: 'RESHEDULE_APPOINTMENT_SUCCESS',
  RESHEDULE_APPOINTMENT_ERROR: 'RESHEDULE_APPOINTMENT_ERROR',
}
export const AddTimeSlotsConstant = {
  ADD_TIME_SLOTS_LOADING: 'ADD_TIME_SLOTS_LOADING',
  ADD_TIME_SLOTS_SUCCESS: 'ADD_TIME_SLOTS_SUCCESS',
  ADD_TIME_SLOTS_ERROR: 'ADD_TIME_SLOTS_ERROR',
}
